// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7V0sP6xMKb-5CJ-LQ0AV1M1QYye6_ok0',
    appId: '1:653968092227:web:ff8a54eab5af0b228eb8f6',
    messagingSenderId: '653968092227',
    projectId: 'footwear-mms',
    authDomain: 'footwear-mms.firebaseapp.com',
    storageBucket: 'footwear-mms.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDC8aFu6AG7hJtAL_jotPczcJJQeRF31pw',
    appId: '1:653968092227:android:dae8745b1b7931c58eb8f6',
    messagingSenderId: '653968092227',
    projectId: 'footwear-mms',
    storageBucket: 'footwear-mms.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5DQ9DByNN-ZHyIBIv8MyNWIg50waGBLg',
    appId: '1:653968092227:ios:9f3b8f51e8da2e328eb8f6',
    messagingSenderId: '653968092227',
    projectId: 'footwear-mms',
    storageBucket: 'footwear-mms.firebasestorage.app',
    iosBundleId: 'com.example.footwearMms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5DQ9DByNN-ZHyIBIv8MyNWIg50waGBLg',
    appId: '1:653968092227:ios:9f3b8f51e8da2e328eb8f6',
    messagingSenderId: '653968092227',
    projectId: 'footwear-mms',
    storageBucket: 'footwear-mms.firebasestorage.app',
    iosBundleId: 'com.example.footwearMms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7V0sP6xMKb-5CJ-LQ0AV1M1QYye6_ok0',
    appId: '1:653968092227:web:0babbc8ba3513a548eb8f6',
    messagingSenderId: '653968092227',
    projectId: 'footwear-mms',
    authDomain: 'footwear-mms.firebaseapp.com',
    storageBucket: 'footwear-mms.firebasestorage.app',
  );

}